language: cpp
sudo: require
dist: xenial

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty

python:
  - 3.7

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="export CC=gcc-8; export CXX=g++-8;"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: *all_sources
          packages:
            - g++-8
            - clang-6.0
      env:
        - MATRIX_EVAL="export CC=clang-6.0; export CXX=clang++-6.0;"

before_install:
  # Update compilers
  - eval "${MATRIX_EVAL}"
  - echo "CC=$CC CXX=$CXX"
  - wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3-linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - cmake --version

script:
  # unit tests
  - cmake -Htest -Bbuild/test
  - cmake --build build/test --target test-verbose
  # build examples
  - python3 examples/build_all.py
